
services:
  postgres:
    image: postgres:16
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      labnet2:
        ipv4_address: 172.16.2.2

networks:
  labnet2:
    external: true
